apiVersion: expiringsecrets.stakater.cloud/v1alpha1
kind: Monitor
metadata:
  labels:
    app.kubernetes.io/name: expiring-secrets
    app.kubernetes.io/managed-by: kustomize
  name: monitor-sample
spec:
  # TODO(user): Add fields here
