apiVersion: expiringsecrets.stakater.com/v1alpha1
kind: Monitor
metadata:
  name: monitor-sample
spec:
  service: docker.io
  secretRef:
    name: personal-access-token
  alertThresholds:
    infoDays: 30
    warningDays: 14
    criticalDays: 7
