name: Pull request for documentation changes

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
    paths:
      - 'README.md'
      - '.markdownlint.yaml'
      - '.vale.ini'
      - '**/*.md'

jobs:
  doc_qa:
    uses: stakater/.github/.github/workflows/pull_request_doc_qa.yaml@v0.0.148
    with:
      MD_CONFIG: .github/md_config.json
      DOC_SRC: README.md
      MD_LINT_CONFIG: .markdownlint.yaml