name: "Kubernetes E2E Tests"

on:
  pull_request_review:
    types:
      - submitted

  pull_request:
    types:
      - labeled
jobs:
  verify-label:
    name: Verify Label
    if: ${{ github.event.review.state == 'approved' || github.event.label.name == 'ok-to-test/kubernetes' }}
    runs-on: ubuntu-latest
    steps:
    - name: Remove the test label
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: ok-to-test/kubernetes

  e2e-tests:
    name: Run E2E Tests
    needs: verify-label
    if: ${{ needs.verify-label.result == 'success' }}

    permissions:
      contents: read
      pull-requests: read
      
    uses: stakater/.github/.github/workflows/operator_e2e.yaml@main
    secrets:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      CONTAINER_REGISTRY_USERNAME: stakater-user
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
      STAKATER_AB_REPOS: ${{ secrets.STAKATER_AB_REPOS }}
    with:
      ENABLE_STAKATER_AB_GIT_AUTH: true